Create table factory(id int, name varchar(30), owner_name varchar(30), ceo varchar(30),manager varchar(30),country varchar(30),state varchar(30),district varchar(30),city varchar(30),website varchar(30),hr varchar(15),since int,  product varchar(30),no_of_employess int,phone bigint,open boolean,working boolean,branch varchar(30),headoffice varchar(30),partner varchar(30),foreign key(id)references person(id));
insert into factory values(10,"tata steel","kapil ","suresh","jayapadma","india","karnataka","chikamagalur","n r pura","tatasteel.com","hamsa",1923,"glass",1000000,1587896643,false,true,"manglore","india","savitha");
insert into factory values(9,"upl ltd","devakar","rathnakar","rohini","usa","washington","dc","new york","uplltd.com","lakshmi",1960,"consmatics",750000,2056893,false,true,"nohida","udupi","darmashesha");
insert into factory values(8,"jsw steel","prakesh","subba roa","deepa","canada","manitoba","nova soctia","toronto","jsw.com","neha",1955,"bottle",650000,1930893124,true,false,"harnaya","mysore","meera");
insert into factory values(7,"tata motors","pavithra","mahesh","nisha","england","scottland","birmin","london","tatamotors.com","nidha",1944,"furniture",300000,19404563894,true,false,"mumbai","banglore","mahesh");
insert into factory values(6,"mahindra and mahindra","pavan","tarun","ranjitha","france","franche","ilde","paryes","mahindr.com","ganesh",1933,"candy",200000,1955786345,true,false,"pune","kolkata","narendra");
insert into factory values(5,"abb india","ravi","shankar","sunila","egypt","port said","aswan","paries","abb.com","kavitha",1983,"cloths",150000,196345632,true,false,"chennai","china","nagendra");
insert into factory values(4,"acb india","chethan","devakar","kavitha","italy","matera","veneto","rome","acb.com","lokesh",1953,"cement",6000000,198578962,true,false,"mysore","japan","haveesh");
insert into factory values(3,"acc ltd","rakesh","venkat","lakshmi","nepal","lumibni","lalitpur","kathmandu","acc.com","dinesh",1933,"camera",50000,19957895,true,false,"banglore","india","avenash");
insert into factory values(2,"ais ltd","suresh","indushekar","tanuja","bhutan","linkdozoda","dagan","propo","ais.com","raveesh",1924,"tv",45000,19354562,true,false,"hydrabad","canada","jagadeesh");
insert into factory values(1,"ashok leyland","ramesh","jayram","indu","austrila","new soth wales","kirra","sydney","ashokalyland.com","shweetha",1925,"truck",12000,21545678,true,false,"karnataka","usa","deepak");
select * from factory;
select * from factory where name="ais ltd";
select * from factory where branch="rathnakar" and hr="ravathi";
select * from factory where country="india" or since=50;
select * from factory id between 1 and 5;
select * from factory where id in(5,10);
select * from factory where id not in (5,6);
select sum(id);
select avg(since);
select count(*);
select max(no_of_employees);
select min(since);
select * from person group by country;
select * from person group by country having country="india";
update person set since=1966 where name="suresh";
drop table person;
alter table person rename to factory_details;
select person.lnasme as Ltable,factory.name as Rtable  from person right join factory on factory.name=factory.name;
select person.id as Ltable,factory.name as Rtable  from person left join factory on person.id=factory.name;
select father_name from person where fname=(select ownwer from factory where headoffice="india");
create view factory_details as select name,ceo from factory;

