CREATE TABLE state_info (sl_no int,state varchar(30), capital varchar(30),CM varchar(30),population bigint,area bigint, no_of_disticts int,language varchar(30),state_dance varchar(30),governor varchar(30));
SELECT * FROM   state_info;
INSERT INTO state_info values(1,'karnataka',' Bangalore.','Basavaraj Bommai',61130704,191791,31,'kannada','yakshagana','Thawarchand Gehlot');
INSERT INTO state_info values(2,'tamil nadu','chennai','M. K. Stalin',72147030,130058,38,'tamil','Bharatanatyam','R. N. Ravi');
INSERT INTO state_info values(3,'kerala','Thiruvananthapuram','Pinarayi Vijayan',34630192,38863 ,14,'malayalam','Kathakali','Arif Mohammad Khan');
INSERT INTO state_info values(4,'goa',' panochi','Pramod Sawant ',1458545,3702,2,'konkani','Dhalo','P. S. Sreedharan Pillai');
INSERT INTO state_info values(5,'Andhra Pradesh',' Amaravati','	Y. S. Jaganmohan Reddy',49386799,162975,26,'telugu','kuchipudi','Biswabhusan Harichandan');
INSERT INTO state_info values(6,'punjab','	Chandigarh','Bhagwant Mann ',27743338,50362 ,23,'punjabi','Bhangra','Banwarilal Purohit');
INSERT INTO state_info values(7,'assam',' Dispur','Himanta Biswa Sarma',31169272,78438,35,'assami','bihu','Jagdish Mukhi');
INSERT INTO state_info values(8,'Himachal Pradesh',' Shimla ','Jai Ram Thakur ',6864602,55673,14,'hindi','','Rajendra Arlekar');
INSERT INTO state_info values(9,'uttar pradesh',' lucknow','Yogi Adityanath',241066874,240928,75,'hindi','yakshagana','	Anandiben Pate');
INSERT INTO state_info values(10,'uttharkhand',' deharadun','Pushkar Singh Dhami',10086292,53483,31,'hindi','yakshagana','Gurmit Singh');
INSERT INTO state_info values(11,'nagaland',' kohima','	Neiphiu Rio ',1980602,16579,16,'english','yakshagana','Jagdish Mukhi');
INSERT INTO state_info values(12,'rajasthan',' jaipur','Kalraj Mishra',685408,342239,31,'hindi','yakshagana','Ashok Gehlot');
INSERT INTO state_info values(13,'bihar',' patna','	Nitish Kumar',104099452,94163,38,'hindi','yakshagana','Phagu Chauhan');
INSERT INTO state_info values(14,'gujrat',' gandhinagar','Bhupendrabhai Patel',60439692,162024,31,'gujrati','yakshagana','Acharya Dev Vrat');
INSERT INTO state_info values(15,'madya pradesh',' bopal.','Shivraj Singh Chouhan',72686209,208345,31,'hindi','yakshagana','	Mangubhai C. Patel');
INSERT INTO state_info values(16,'haryana',' chandigrah','Manohar Lal Khattar',25351462,44212,22,'hindi','yakshagana','Thawarchand Gehlot');
INSERT INTO state_info values(17,'west bengal',' kolkata','amith',42130704,191791,31,'hindi','yakshagana','Thawarchand Gehlot');
INSERT INTO state_info values(18,'maharastra',' mumbai','jaideep',56330704,191791,31,'hindi','yakshagana','Thawarchand Gehlot');
INSERT INTO state_info values(19,'odisha',' Buvaneshwar','arun kumar',6456130704,191791,31,'hindi','yakshagana','Thawarchand Gehlot');
INSERT INTO state_info values(20,'manipur',' imphal','lakesh',61130704,191791,31,'hindi','yakshagana','Thawarchand Gehlot');
SELECT * FROM state_info;
SELECT * FROM state_info where sl_no=1 and state='karnataka';
SELECT * FROM state_info where sl_no=3 and language='malayalam';
SELECT * FROM state_info where sl_no=2 and capital=' chennai';
SELECT * FROM state_info where sl_no=18 and state='maharastra';
SELECT * FROM state_info where sl_no=19 and no_of_disticts=31;
SELECT * FROM state_info where sl_no=1 or state='kerala';
SELECT * FROM state_info where sl_no=10 or language='hindi';
SELECT * FROM state_info where sl_no=2 or capital=' dispur';
SELECT * FROM state_info where sl_no=18 and state='karnataka';
SELECT * FROM state_info where sl_no=19 and no_of_disticts=31;
SELECT COUNT(sl_no) from state_info;
SELECT COUNT(population) from state_info;
SELECT COUNT(area) from state_info;
SELECT COUNT(no_of_disticts) from state_info;
SELECT COUNT(sl_no) from state_info;
SELECT MAX(sl_no) from state_info;
SELECT MAX(area) from state_info;
SELECT MAX(population) from state_info;
SELECT MAX(no_of_disticts) from state_info;
SELECT MAX(sl_no) from state_info;
SELECT MIN(sl_no) from state_info;
SELECT MIN(area) from state_info;
SELECT MIN(population) from state_info;
SELECT MIN(no_of_disticts) from state_info;
SELECT MIN(sl_no) from state_info;
 SELECT * FROM state_info WHERE sl_no in(10,15);
 SELECT * FROM state_info WHERE sl_no in(10,15);
  SELECT * FROM state_info WHERE sl_no in(11,20);
   SELECT * FROM state_info WHERE sl_no in(10,20);
    SELECT * FROM state_info WHERE sl_no in(5,11);
    SELECT * FROM state_info WHERE sl_no  not in(10,15);
 SELECT * FROM state_info WHERE state  not in('kerala');
  SELECT * FROM state_info WHERE sl_no  not in(11,20);
   SELECT * FROM state_info WHERE sl_no not  in(10,20);
    SELECT * FROM state_info WHERE sl_no  not in(5,11);
SELECT avg(sl_no) from state_info;
SELECT AVG(area) from state_info;
SELECT AVG(population) from state_info;
SELECT AVG(no_of_disticts) from state_info;
SELECT AVG(sl_no) from state_info;
SELECT * FROM state_info where state like 'k%';
SELECT * FROM state_info where state like 'a%';
SELECT capital FROM state_info where state like 'k%';
SELECT state FROM state_info where state like 'a%';
SELECT * FROM state_info where state like 'p%';
SELECT capital FROM state_info where state like 'm%';
SELECT capital FROM state_info where state like '%a';
SELECT * FROM state_info where state like '%l';
SELECT * FROM state_info where state like '%a%';
SELECT * FROM state_info where state like '%i%';
SELECT upper(capital) FROM state_info;
SELECT UPPER(state) FROM state_info;
SELECT UPPER(CM) FROM state_info;
SELECT UPPER(language) FROM state_info;
SELECT LOWER(capital) FROM state_info;
SELECT LOWER(language) FROM state_info;
SELECT LOWER(state) FROM state_info;
SELECT LOWER(CM) FROM state_info;
SELECT LOWER(governor) FROM state_info;
SELECT CONCAT(state, capital) from state_info;
SELECT CONCAT(state, CM) from state_info;
SELECT CONCAT(state, language) from state_info;
SELECT CONCAT(state, area) from state_info;
SELECT CONCAT( capital,state) from state_info;
SELECT INSTR('banglore','b') AS position;
SELECT INSTR('state','t')  AS position;
SELECT INSTR('capital','l') AS location;
SELECT INSTR('XWORKZ','K') AS position;
SELECT INSTR('smruthi','u') AS position;
SELECT * FROM state_info WHERE state between 'a' and 'h';
SELECT capital FROM state_info WHERE state between 'a' and 'h';
SELECT state FROM state_info WHERE state between 'a' and 'r';
SELECT SUBSTR('SMRUTHI',1,4)as substring;
SELECT SUBSTR(state,3,9) FROM state_info;
SELECT SUBSTR(capital,5,10) FROM state_info;
SELECT SUBSTR(CM,10,15) FROM state_info;
SELECT SUBSTR(state,10,15) FROM state_info;



select * from state_info

    
 

